const CALLBLOCK_TYPES = {
    BLOCK_MIN: 'CALLBLOC',
    BLOCK_CAT: 'CALLBLOCKS',
    CALLBLOCKS_LIST: 'CALLBLOCKS_LIST',
    CALLBLOCKS_LISTS: 'CALLBLOCKS_LISTS',
    CALLBLOCK_LIST: 'CALLBLOCK_LIST',
};